### PR TITLE
Readonly cache

### LINKED ISSUE #53: read-only cache support
**Current behavior:**
Tuples objects are transient. i.e. It goes away when rule engine shuts down.

**Expected behavior:**
Selected tuple data to be available via cache regardless of a rule engine instance's lifecycle.

**What is the motivation / use case for changing the behavior?**
Long lasting factual data such as employee record would need to be more persistent compared to event data. Tuple object management should support such cases more natively.

### PR DESCRIPTION
**Pull request by jpark800**
First step in the cache support. Fixes #53.

### CODE REVIEW

**Comment by balamg** [comment]
What you need is an on-event hook..(called "pre-processor" in BE) This is the place where you can load necessary tuples from the store. Also this needs to be integrated with the rule session api with a "Store" interface.
Incidentally I have a WIP branch that addresses the store interface and some more (like an interface to externalise join tables themselves and an in-memory implementation of those) Perhaps you can use that as the starting point for implementing your Solr/Redis store?

**Comment by balamg** [comment]
Take a look at the 'store' branch to start with.

**Comment by jpark800** [comment]
@balamg Sure, will take a look.

**Comment by jpark800** [comment]
After reviewing the WIP store branch, it would be best to merge the two branches first. The merge should include direct tuple integration with redis, TupleType based secondary index, multi store support, pre-processor(or startup) time tuple loading and tuple update propagation to clustered engines. Thus closing the PR.

**Pull request closed without merging**
