### PR TITLE
Issue80

### PR DESCRIPTION
**Pull request by balamg**
This addresses #80 A new method `ReplayTuplesForRule` to bootstrap a rule with existing tuples has been added. To address #80, call this method right after `AddRule`

### CODE REVIEW

**Comment by rameshpolishetti** [comment]
@balamg I tried to reproduce the scenario and found the below case is failing:
1. Add a rule
2. assert some events
3. remove the rule
4. add the same rule again
5. assert remaining events
6. expect rule action being fired

go testcase:
```
func TestGitIssue80_2(t *testing.T) {
	rs, _ := createRuleSession()

	// create rule
	r1 := ruleapi.NewRule("Rule1")
	r1.AddCondition("r1c1", []string{"t1.none", "t2.none"}, trueCondition, nil)
	r1.SetAction(r1Action)
	// create tuples
	t1, _ := model.NewTupleWithKeyValues("t1", "one") // No TTL
	t2, _ := model.NewTupleWithKeyValues("t2", "two") // TTL is 0

	// start rule session
	rs.Start(nil)

	assertCtxValues := make(map[string]interface{})
	assertCtxValues["test"] = t
	assertCtxValues["actionFired"] = "NOTFIRED"
	assertCtx := context.WithValue(context.TODO(), "values", assertCtxValues)

	// Test1: add r1 and assert t1 & t2; rule action SHOULD be fired
	addRule(t, rs, r1)
	assert(assertCtx, rs, t1)
	assert(assertCtx, rs, t2)
	actionFired, _ := assertCtxValues["actionFired"].(string)
	if actionFired != "FIRED" {
		t.Log("rule action SHOULD be fired")
		t.FailNow()
	}

	// Test2: remove r1 and assert t2; rule action SHOULD NOT be fired
	deleteRule(t, rs, r1)
	assertCtxValues["actionFired"] = "NOTFIRED"
	assert(assertCtx, rs, t2)
	actionFired, _ = assertCtxValues["actionFired"].(string)
	if actionFired != "NOTFIRED" {
		t.Log("rule action SHOULD NOT be fired")
		t.FailNow()
	}

	// Test3: add r1 again and assert t2; rule action SHOULD be fired
	addRule(t, rs, r1)
	assertCtxValues["actionFired"] = "NOTFIRED"
	assert(assertCtx, rs, t2)
	actionFired, _ = assertCtxValues["actionFired"].(string)
	if actionFired != "FIRED" {
		t.Log("rule action SHOULD be fired")
		t.FailNow()
	}

	rs.Unregister()
}

func addRule(t *testing.T, rs model.RuleSession, rule model.Rule) {
	err := rs.AddRule(rule)
	if err != nil {
		t.Logf("[%s] error while adding rule[%s]", time.Now().Format("15:04:05.999999"), rule.GetName())
		return
	}
	t.Logf("[%s] Rule[%s] added. \n", time.Now().Format("15:04:05.999999"), rule.GetName())
}

func deleteRule(t *testing.T, rs model.RuleSession, rule model.Rule) {
	rs.DeleteRule(rule.GetName())
	t.Logf("[%s] Rule[%s] deleted. \n", time.Now().Format("15:04:05.999999"), rule.GetName())
}

func assert(ctx context.Context, rs model.RuleSession, tuple model.Tuple) {
	assertCtxValues := ctx.Value("values").(map[string]interface{})
	t, _ := assertCtxValues["test"].(*testing.T)
	err := rs.Assert(ctx, tuple)
	if err != nil {
		t.Logf("[%s] assert error %s", time.Now().Format("15:04:05.999999"), err)
	}
}

func r1Action(ctx context.Context, rs model.RuleSession, ruleName string, tuples map[model.TupleType]model.Tuple, ruleCtx model.RuleContext) {
	assertCtxValues := ctx.Value("values").(map[string]interface{})
	test, _ := assertCtxValues["test"].(*testing.T)

	t := tuples["t1"]
	tSrt, _ := t.GetString("id")
	test.Logf("[%s] r1Action called with the tuple[%s] \n", time.Now().Format("15:04:05.999999"), tSrt)

	assertCtxValues["actionFired"] = "FIRED"
}
````

**Comment by balamg** [comment]
I don't see the new api method being used. After "Test2" and before "Test3" can you `rs.ReplayTuplesForRule(r1)`

**Comment by rameshpolishetti** [comment]
Got it @balamg 
It worked after adding ```rs.ReplayTuplesForRule(r1)```

**Comment by balamg** [comment]
@rameshpolishetti Can you add your test case to the PR branch and merge it to master, thanks

**Comment by flogo-oss** [comment]
[CLA assistant check](https://flogo.cla.cloud.tibco.com:443/project-flogo/rules?pullRequest=84) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://flogo.cla.cloud.tibco.com:443/project-flogo/rules?pullRequest=84) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: balamg<br/>:x: rameshpolishetti<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://flogo.cla.cloud.tibco.com:443/check/project-flogo/rules?pullRequest=84) it.</sub>

**Pull request merged**
