### PR TITLE
Feature invoke activity

### PR DESCRIPTION
**Pull request by rameshpolishetti**
This PR implements #69. It enhances rule action function to `service`. A `service` is constructed from a `gofunction` / `flogo activity` / `flogo action`.
When a rules fires, corresponding service input expressions would be resolved from tuple scope and then service gets executed (i.e underlying function/activity/action gets executed).

A service definition goes like this:
```
"services": [
  {
    "name": "ServiceFlowAction",
    "description": "Asynchronous flow action service",
    "type": "action",
    "ref": "github.com/project-flogo/flow",
    "settings": {
      "flowURI": "res://flow:sample_flow"
    }
  }
]
``` 

Invoking the service:
```
"rules": [
  {
    "name": "n1.name == function",
    "conditions": [],
    "actionService": {
      "service": "ServiceFunction",
      "input": {
        "message": "=$.n1.name"
       }
    }
  }
]
```
An example covering all varients of `service` is made available at - examples/flogo/invokeservice

### CODE REVIEW

**Comment by balamg** [comment]
I'd like to see support added for invoking a flow as compared to an activity. That would be a general solution

**Comment by rameshpolishetti** [comment]
@balamg Now I have added support to invoke flogo-action (ex: flow)

**Comment by fm-tibco** [comment]
Maybe you should consider leaving this as invoke activity?  @skothari-tibco is implementing an activity that can invoke actions (not just flows).  This way you have a lot more flexibility.  If someone wants to invoke a simple rest call, they don't have to setup an entire flow for that.

**Comment by rameshpolishetti** [comment]
Thank you @fm-tibco for sharing your input.  Seems my PR message is not conveying enough about rule service in detail. In fact, this PR supports any action (not just flow-action) as rule service, as mentioned below:

"services": [
  {
      "name": "ServiceFlowAction",
      "description": "Asynchronous flow action service",
      "type": "action",   **==> type can be "function" / "activity" / "action"**
      "ref": "github.com/project-flogo/flow",    **==> It can be any flogo-action / flogo-activity reference**
       "settings": {    **==> action/activity specific settings**
           "flowURI": "res://flow:sample_flow"
       }
  }
]
Comprehensive example is made available at: https://github.com/project-flogo/rules/tree/feature-invoke-activity/examples/flogo/invokeservice

Coming back to what to consider here **activity vs action OR both** - my original plan was to have just activity. As per the @balamg view mentioned above, action (_flow_) adds more value to rules.

Appreciate your further inputs.

**Comment by rameshpolishetti** [comment]
closing this PR as an improved version of this feature (invoke activity) is available in develop branch.

**Pull request closed without merging**
