### PR TITLE
Fix for #22 : Expression syntax for rule conditions

### PR DESCRIPTION
**Pull request by balamg**
Instead of writing rule conditions in Go as functions, you can now use an expression syntax which is more intuitive. This reuses the expression syntax used in flogo expressions for the most part. Only tuple property referencing is supported. A tuple property is referenced via `$<tuple-type>.<tuple-property>` Basic validation is done to ensure that the tuple type/property exists as defined. An expression can contain references to multiple types and properties and join conditions will be created implicitly

For example, if you have a `customer` tuple type and an `account` tuple type with a string `accountid` property in both of them, you can write conditions such as
`Rule.AddExprCondition ("$customer.accountid == $account.accountid")` to join the two tuple types of customer/account based on `accountid`

### CODE REVIEW

**Comment by fm-tibco** [comment]
If the intent is for this to use the flogo expression syntax, then this is a little off and a lot of extra work.  The syntax should actually be "$.customer.accountid == $.account.accountid".  This all you have to do is create a "Scope" that has customer and account and it will be resolved for you.  This can be done with just a couple of lines of code.    Also, this allows resolution of things like properties and environment variables for example:  "$.account.debt > $env[DEBT_LIMIT]"

**Comment by mellistibco** [comment]
@balamg any update here RE @fm-tibco's comment?

**Comment by balamg** [comment]
Cannot avoid some amount of parsing and access AST for validations against known `TupleTypes` Further, access to the AST is required as I need to separately evaluate the LHS and RHS of a condition for a join optimization (will come later) Also I think what you are suggesting is that I create a certain type of Scope and populate it with keys/values reading from the tuples. If so, which implementation type should be used? And while setting values in it, should I include the leading '.' Perhaps not but would be good to know

**Comment by balamg** [comment]
If there is no further question or a comment I'd like to merge this PR

**Comment by fm-tibco** [comment]
Can you elaborate on why access to the AST is required and why you cannot use the expression syntax  as is?  Can you give an example?

**Comment by balamg** [comment]
With a join condition such as LHS == RHS, the join optimization would store the evaluation of the LHS in a map structure with the value of LHS as "key"
When joining with the RHS, the RHS would be evaluated and only the matching tuples based on the LHS value from the LHS would be picked up. Right now, a sequential scan is performed.
For similar reasons, for non-equivalent join conditions, a tree map structure would be appropriate. Hence, access to AST is required
Regarding expression evaluation, we need to be able to make a syntax check to ensure that it is a valid Rule Condition. ie, to ensure that in an expression such as 
n1.p1 == n2.p2, that "n1" and "n2" are valid tuple types and "p1" and "p2" are valid properties.
Also note that this needs to run standalone as well, outside of flogo context

**Comment by fm-tibco** [comment]
So is this only in the case of == ?  

Also, the syntax that you are using doesn't match the flogo syntax.  It should be $.n1.p1 == $.n2.p2 

Basically $.  is look up the value in the current scope.  We have support other types of resolvers such as $property, $env.   $[resolver]    where "." indicates the current scope resolver, "env" in environment variable resolver and "property" is an application property resolver.  If needed you can add your own special type of resolver.

**Comment by balamg** [comment]
Non-equiv joins as well, so LHS <=, <,  >, >=, RHS
We could change the syntax to $.n1.p1 to keep it in line with Flogo
Pl comment on `exprcondition.go:Resolve` if this is the correct way to use a custom resolver or if there is a better way to do that. You said "This all you have to do is create a "Scope" that has customer and account and it will be resolved for you." It is not clear to me how to do that. Can you provide an example?

**Comment by balamg** [comment]
@fm-tibco Awating your comment and/or approval

**Comment by mellistibco** [comment]
At a bare min, we need to keep the syntax the same... Also, I would not be worried about making the expression logic work outside the context of Flogo, this is an action built on top of flogo...

Also, what is the performance difference compared to just evaluating the expression every time vs the optimization that you're doing?

**Comment by balamg** [comment]
rules should also be a general purpose API that should be usable from outside the flogo context. We have to keep this in mind and not tightly couple with flogo context
syntax can be kept the same
Its not clear to me how to do it any other way unless someone shows me an example of how to properly use the scope and resolver.
for performance, its O(1) with v/s O(n) -> best/worst cases, for the equiv. joins.

**Comment by balamg** [comment]
Closing this PR as there are significant changes to the expression API in project-flogo/core and this PR is not valid anymore

**Pull request closed without merging**
